# PID of current job: 2144363
mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-SanityCheckData(mSet)
mSet<-RemoveMissingPercent(mSet, percent=0.5)
mSet<-ImputeMissingVar(mSet, method="knn_var")
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "MedianNorm", "LogNorm", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_",1, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 1.5, 0, F, 0.05, TRUE, "fdr")
mSet<-PlotVolcano(mSet, "volcano_1_",1, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 1.5, 0, T, 0.05, TRUE, "fdr")
mSet<-PlotVolcano(mSet, "volcano_2_",1, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 1.5, 0, F, 0.05, TRUE, "fdr")
mSet<-PlotVolcano(mSet, "volcano_3_",1, "png", 72, width=NA)
